Add profile

diff --git a/zebrakow b/zebrakow
--- a/zebrakow
+++ b/zebrakow
@@ -7,6 +7,7 @@ export RUN=""
 export SYSTEMD_RUN_MACHINE=""
 export TERMINAL=""
 export NAME="$(date +%d-%m-%Y-%H:%M:%S)"
+options=()
 
 export RUN_CONTAINER_REMOTE=""
 
@@ -65,6 +66,7 @@ function usage() {
     printf "\t-t\t\tAttach to the terminal\n"
     printf "\t-h\t\tDisplay this help\n"
     printf "\t-S foobar.slice Run under this slice unit\n"
+    printf "\t-P foobar       Run under this profile\n" 
     printf "\t-N foobar   \tSet a name for the job. (DD-MM-YYYY-HH:MM:SS by default)\n"
     printf "\t-j {job} OPT\tOperate on the job (by NAME or by JOB_ID)\n"
     printf "\n\tSuboptions for -j:\n"
@@ -92,7 +94,7 @@ function state() {
     fi
 }
 
-while getopts "H:M:lthN:j:S:" opt; do
+while getopts "H:M:lthN:j:S:P:" opt; do
     case $opt in
 	H)
 	    if [[ "$CONTAINER" != "" ]]; then
@@ -204,8 +206,15 @@ while getopts "H:M:lthN:j:S:" opt; do
 	S)
 	    SLICE_UNIT="--slice $OPTARG"
 	    ;;
-	    
-	:)
+	P)
+	    run /bin/true && \
+		if [[ -e /etc/zebrakow/profiles/$OPTARG.profile ]]; then \
+		    source /etc/zebrakow/profiles/$OPTARG.profile;\
+		else \
+		    echo "Cannot find profile named $OPTARG" >&2 && exit 1;\
+		fi \
+		;;\
+	    :)
 	    echo "Missing option argument for -$OPTARG" >&2;
 	    exit 1
 	    ;;
@@ -215,6 +224,7 @@ done
 shift $((OPTIND-1))
 systemd-run --no-block $SYSTEMD_RUN_MACHINE $SLICE_UNIT $TERMINAL\
 	    -p Type=notify -p NotifyAccess=all \
+	    $(echo ${options[@]}) \
 	    -p ExecStartPre/usr/lib/zebrakow/zebrakow-setup\ --start\ '$INVOCATION_ID'\ '$NAME' \
 	    -p Environment=HOME=/root -p Environment=NAME=$NAME\
 	    -p ExecStopPost/usr/lib/zebrakow/zebrakow-setup\ --stop\ '$INVOCATION_ID' \
