misc fixes for space separarted NAME, remove kill

diff --git a/zebrakow b/zebrakow
--- a/zebrakow
+++ b/zebrakow
@@ -37,8 +37,9 @@ function metadata() {
 	source /etc/machine-info;
     fi
     echo "JOB_ID=$1"
-    echo "CMDLINE=$(cat /proc/"$(systemctl status $UNIT | grep Main\ PID: | sed s/\ Main\ PID:\ //g | awk '{print $1}')"/comm)"
-    echo "TIME=Running $(systemctl status $UNIT | grep Active | sed s/\ \ \ Active:\ active\ \(running\)\ //g)"
+    COMM=$(cat /proc/"$(systemctl status $UNIT | grep Main\ PID: | sed s/\ Main\ PID:\ //g | awk '{print $1}')"/comm)
+    echo "COMM=${COMM}"
+    echo "TIME=Running $(systemctl status $UNIT | grep Active | awk '{print $4 $5 $6 $7 $8 $9 $10 $11}')"
     echo "UNIT=$UNIT"
     echo "SLICE=$(systemctl show -p Slice $UNIT | sed s/Slice=//g )"
     echo "STATUS=$(systemctl status $UNIT | grep Status: | sed s/\ \ \ Status:\ //g)"
@@ -65,18 +66,18 @@ function usage() {
     printf "\t-l\t\tList running jobs\n"
     printf "\t-t\t\tAttach to the terminal\n"
     printf "\t-h\t\tDisplay this help\n"
-    printf "\t-c\t\tClean all jobs"
+    printf "\t-c\t\tClean all jobs\n"
     printf "\t-S foobar.slice Run under this slice unit\n"
     printf "\t-P foobar       Run under this profile\n" 
     printf "\t-N foobar   \tSet a name for the job. (DD-MM-YYYY-HH:MM:SS by default)\n"
-    printf "\t-j {job} OPT\tOperate on the job (by NAME or by JOB_ID)\n"
+    printf "\t-j {job} OPT\tOperate on the job by ID\n"
     printf "\n\tSuboptions for -j:\n"
     printf "\t-u\tView logs for the job\n"
     printf "\t-f\tFollow the build log of a running job\n"
     printf "\t-m\tDisplay metadata of a running job\n"
     printf "\t-s\tDisplay status of a running job's unit\n"
     printf "\t-i\tInspect the unit file of a running job\n"
-    printf "\t-k\tKill the job\n"
+    printf "\t-k\tStop the job\n"
     printf "\nExamples:\n"
     printf "$ %s -H root@remote.host:container -j zxc887as676a9s8d79as7d21389as2913 -k\n" $0
     exit 0
@@ -129,18 +130,18 @@ while getopts "H:M:lthcN:j:S:P:" opt; do
 	    ;;
 	t)
 	    TERMINAL="--pty"
-	    unset $NO_BLOCK
+	    NO_BLOCK=""
 	    ;;
 	h)
 	    usage;;
 	c)
-	    run rm -rf /run/zebrakow
+	    run rm -rfi /run/zebrakow
 	    exit $?
 	    ;;
 	N)
 	    echo "Checking name..."
 	    run /bin/true && \
-		if grep \\b$OPTARG\\b < <(ls -lR /run/zebrakow/) >/dev/null; then \
+		if grep \\b"$OPTARG"\\b < <(ls -lR /run/zebrakow/) >/dev/null; then \
 		    echo "A job with this name already exists" && exit 1;fi
 	    if [[ ${#OPTARG} -le 30 && ${#OPTARG} -gt 0 ]]; then
 		NAME=$OPTARG
@@ -155,9 +156,9 @@ while getopts "H:M:lthcN:j:S:P:" opt; do
 		JOB_ID=$OPTARG
 		TYPE=1
 	    elif [[ ${#OPTARG} -le 30 ]]; then
-		NAME=$OPTARG
+		NAME="${OPTARG}"
 	    else
-		echo "Invalid spec for NAME or JOB_ID passed. Please pass one of -j or -N, and names less than 30 characters." >&2
+		echo "Invalid spec for JOB_ID passed. Please pass a 32 character valid JOB_ID." >&2
 		exit 1
 	    fi
 	    run /bin/true && \
@@ -203,9 +204,9 @@ while getopts "H:M:lthcN:j:S:P:" opt; do
 			;;\
 		    -k)\
 			if state $JOB_ID; then \
-			    systemctl kill $UNIT; exit $?; \
+			    systemctl stop $UNIT; exit $?; \
 			else \
-			    echo "Cannot kill a non-running job." >&2 && exit 1; \
+			    echo "Cannot stop a non-running job." >&2 && exit 1; \
 			fi \
 			;;\
 		    *)\
@@ -235,9 +236,7 @@ done
 
 shift $((OPTIND-1))
 systemd-run $NO_BLOCK $SYSTEMD_RUN_MACHINE $SLICE_UNIT $TERMINAL \
-	    -p Type=notify -p NotifyAccess=all \
-	    "${options[@]}" \
-	    -p ExecStartPre=/usr/lib/zebrakow/zebrakow-setup\ --start\ '$INVOCATION_ID'\ '$NAME' \
-	    -p Environment=HOME=/root -p Environment=NAME=$NAME\
-	    -p ExecStopPost=/usr/lib/zebrakow/zebrakow-setup\ --stop\ '$INVOCATION_ID' \
+	    -p Type=notify -p NotifyAccess=all "${options[@]}" \
+	    -p ExecStartPre=/usr/lib/zebrakow/zebrakow-setup\ --start\ '$INVOCATION_ID'\ "${NAME}" \
+	    -p Environment=HOME=/root -p ExecStopPost=/usr/lib/zebrakow/zebrakow-setup\ --stop\ '$INVOCATION_ID' \
 	    "$@"
